### ISSUE TITLE
Merge efforts to official ServiceStack.Azure project

### ISSUE THREAD

**Issue by mythz** [onlyann/ServiceStack.AzureServiceBus#1]
Hi, I didn't notice that you created your own implementation until I just found it on NuGet. We've just deployed MQ Support for Azure Service Bus in our latest v4.5.14 Release which is being maintained in:

https://github.com/ServiceStack/ServiceStack.Azure

It would be a good if we could combine our efforts on the official package which gets deployed in lock-step in each ServiceStack release and will likely be the impl that will be used the most. If you have plans on adding more features in future we'd be happy to make you a contributor so you can get direct contributor access to make changes.

Otherwise if you're happy to continue working on your impl that's cool too, just thought I'd touch base to see if there's potential to reduce duplicated efforts.

**Comment by onlyann** [comment]
Hi @mythz ,

I recently read about your latest release (which is impressive by the way).  
 I started this project to fill the gap with the hope that Azure Service Bus will eventually be officially supported and it just happens you release an official support at about the same time.

I plan to complete a few remaining features on this repository and am happy to help on the official package where I can. 

At the moment, there are a few differences with the official package, mainly because you have the additional challenge to maintain an API that is consistent with both full .NET and .NET Core while I have taken the approach to focus on the full .NET framework until [azure-service-bus-dotnet]( https://github.com/Azure/azure-service-bus-dotnet) gets closer to completion.

I'll retire this repository once the official package provides similar features or if I feel it is not helping the ServiceStack community.

I will add a disclaimer soon in the readme to avoid confusion.
